//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.democratia.view.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.democratia.view.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse postle.
        /// </summary>
        public static string adress {
            get {
                return ResourceManager.GetString("adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre compte a bien été modifié.
        /// </summary>
        public static string bienModifier {
            get {
                return ResourceManager.GetString("bienModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nous espérons vous revoir bientôt.
        /// </summary>
        public static string bienSupp {
            get {
                return ResourceManager.GetString("bienSupp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quelle bonne idée de nous rejoindre.
        /// </summary>
        public static string BonneNouvelle {
            get {
                return ResourceManager.GetString("BonneNouvelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Budget.
        /// </summary>
        public static string budget {
            get {
                return ResourceManager.GetString("budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La somme des budget de chaque thème est inférieur au budget total donné.
        /// </summary>
        public static string budgetInsuffisant {
            get {
                return ResourceManager.GetString("budgetInsuffisant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vérifier que tous les champs soient complets.
        /// </summary>
        public static string champComplet {
            get {
                return ResourceManager.GetString("champComplet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vos changements ont été pris en compte et seront appliqués au prochain démarrage de l&apos;application.
        /// </summary>
        public static string ChangementOk {
            get {
                return ResourceManager.GetString("ChangementOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Changement Réussi.
        /// </summary>
        public static string changementReussi {
            get {
                return ResourceManager.GetString("changementReussi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisir une image sur votre appareil.
        /// </summary>
        public static string choixImage {
            get {
                return ResourceManager.GetString("choixImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Claire.
        /// </summary>
        public static string claire {
            get {
                return ResourceManager.GetString("claire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Création de compte réussi, Connectez-vous maintenant.
        /// </summary>
        public static string compteCree {
            get {
                return ResourceManager.GetString("compteCree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;adresse mail est déjà utilisé.
        /// </summary>
        public static string compteExistantErreur {
            get {
                return ResourceManager.GetString("compteExistantErreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Oui, supprimez mon compte.
        /// </summary>
        public static string confirmeSupp {
            get {
                return ResourceManager.GetString("confirmeSupp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous vraiment quitter l&apos;application ?.
        /// </summary>
        public static string confirmQuitt {
            get {
                return ResourceManager.GetString("confirmQuitt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Se connecter.
        /// </summary>
        public static string connecter {
            get {
                return ResourceManager.GetString("connecter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de connexion inattendu.
        /// </summary>
        public static string connexionErreur {
            get {
                return ResourceManager.GetString("connexionErreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Continuer.
        /// </summary>
        public static string continuer {
            get {
                return ResourceManager.GetString("continuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Couleur représentative.
        /// </summary>
        public static string CouleurRepre {
            get {
                return ResourceManager.GetString("CouleurRepre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Création d&apos;un groupe.
        /// </summary>
        public static string creaGroupe {
            get {
                return ResourceManager.GetString("creaGroupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrer.
        /// </summary>
        public static string enregistrer {
            get {
                return ResourceManager.GetString("enregistrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrez le nom de votre groupe.
        /// </summary>
        public static string entrezNomGroupe {
            get {
                return ResourceManager.GetString("entrezNomGroupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez remplir le champ {0}.
        /// </summary>
        public static string erreurChamp {
            get {
                return ResourceManager.GetString("erreurChamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors de la création du compte.
        /// </summary>
        public static string erreurCreation {
            get {
                return ResourceManager.GetString("erreurCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors de la récupération des données.
        /// </summary>
        public static string erreurDonne {
            get {
                return ResourceManager.GetString("erreurDonne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur inattendu, veuillez revenir ultérieurement.
        /// </summary>
        public static string erreurInattendu {
            get {
                return ResourceManager.GetString("erreurInattendu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors de la capture de la photo.
        /// </summary>
        public static string erreurPhoto {
            get {
                return ResourceManager.GetString("erreurPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez saisir votre adresse mail.
        /// </summary>
        public static string errorMailMessage {
            get {
                return ResourceManager.GetString("errorMailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez saisir votre mot de passe.
        /// </summary>
        public static string errorPasswordMessage {
            get {
                return ResourceManager.GetString("errorPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un champ requiert est vide.
        /// </summary>
        public static string errorUnknowEmptyFieldMessage {
            get {
                return ResourceManager.GetString("errorUnknowEmptyFieldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La discussion prend fin le .
        /// </summary>
        public static string finDiscussion {
            get {
                return ResourceManager.GetString("finDiscussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le format de l&apos;adresse mail est incorrecte.
        /// </summary>
        public static string formatEmail {
            get {
                return ResourceManager.GetString("formatEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le format du mot de passe est incorrecte.
        /// </summary>
        public static string formatMotDePasse {
            get {
                return ResourceManager.GetString("formatMotDePasse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Galerie.
        /// </summary>
        public static string galerie {
            get {
                return ResourceManager.GetString("galerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mes groupes.
        /// </summary>
        public static string groupe {
            get {
                return ResourceManager.GetString("groupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce groupe ne contient aucune proposition.
        /// </summary>
        public static string groupeSansProposition {
            get {
                return ResourceManager.GetString("groupeSansProposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à S&apos;indentifier.
        /// </summary>
        public static string Identifiant {
            get {
                return ResourceManager.GetString("Identifiant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M&apos;inscrire.
        /// </summary>
        public static string inscription {
            get {
                return ResourceManager.GetString("inscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Langue.
        /// </summary>
        public static string Langage {
            get {
                return ResourceManager.GetString("Langage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à courriel.
        /// </summary>
        public static string mail {
            get {
                return ResourceManager.GetString("mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenu.
        /// </summary>
        public static string malModif {
            get {
                return ResourceManager.GetString("malModif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur de suppresssion est survenu.
        /// </summary>
        public static string malSupp {
            get {
                return ResourceManager.GetString("malSupp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Êtes-vous sûr(e) de vouloir supprimer le compte ?.
        /// </summary>
        public static string mauvaiseNouvelle {
            get {
                return ResourceManager.GetString("mauvaiseNouvelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe incorrecte.
        /// </summary>
        public static string mauvaisMdp {
            get {
                return ResourceManager.GetString("mauvaisMdp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe.
        /// </summary>
        public static string Mdp {
            get {
                return ResourceManager.GetString("Mdp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier mon compte.
        /// </summary>
        public static string ModifCompte {
            get {
                return ResourceManager.GetString("ModifCompte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer en un !.
        /// </summary>
        public static string NewCompte {
            get {
                return ResourceManager.GetString("NewCompte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer un groupe.
        /// </summary>
        public static string NewGroupe {
            get {
                return ResourceManager.GetString("NewGroupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        public static string Nom {
            get {
                return ResourceManager.GetString("Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Durée de la discussion (en jour).
        /// </summary>
        public static string nombreJourDiscus {
            get {
                return ResourceManager.GetString("nombreJourDiscus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Durée d&apos;un vote (en jour).
        /// </summary>
        public static string nombreJourVote {
            get {
                return ResourceManager.GetString("nombreJourVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nom du groupe est requis.
        /// </summary>
        public static string nomGroupeRequis {
            get {
                return ResourceManager.GetString("nomGroupeRequis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Non.
        /// </summary>
        public static string non {
            get {
                return ResourceManager.GetString("non", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pas d&apos;utilisateur trouvé.
        /// </summary>
        public static string noUser {
            get {
                return ResourceManager.GetString("noUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Soumettre une nouvelle proposition.
        /// </summary>
        public static string nouvellProp {
            get {
                return ResourceManager.GetString("nouvellProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Oui.
        /// </summary>
        public static string oui {
            get {
                return ResourceManager.GetString("oui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pas de compte ?.
        /// </summary>
        public static string pasCompte {
            get {
                return ResourceManager.GetString("pasCompte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à photo.
        /// </summary>
        public static string photo {
            get {
                return ResourceManager.GetString("photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Préférences.
        /// </summary>
        public static string preference {
            get {
                return ResourceManager.GetString("preference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à prénom.
        /// </summary>
        public static string prenom {
            get {
                return ResourceManager.GetString("prenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quitter l&apos;application maintenant.
        /// </summary>
        public static string quitterApp {
            get {
                return ResourceManager.GetString("quitterApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MainPage.
        /// </summary>
        public static string retourConnexion {
            get {
                return ResourceManager.GetString("retourConnexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Home.
        /// </summary>
        public static string retourHome {
            get {
                return ResourceManager.GetString("retourHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selectionner.
        /// </summary>
        public static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionner une autre image.
        /// </summary>
        public static string selectAutreImage {
            get {
                return ResourceManager.GetString("selectAutreImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionner une image.
        /// </summary>
        public static string selectImage {
            get {
                return ResourceManager.GetString("selectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionner une langue.
        /// </summary>
        public static string selectionLangue {
            get {
                return ResourceManager.GetString("selectionLangue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionner un thème.
        /// </summary>
        public static string selectionTheme {
            get {
                return ResourceManager.GetString("selectionTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sombre.
        /// </summary>
        public static string sombre {
            get {
                return ResourceManager.GetString("sombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suivant.
        /// </summary>
        public static string suivant {
            get {
                return ResourceManager.GetString("suivant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer mon compte.
        /// </summary>
        public static string SuppCompte {
            get {
                return ResourceManager.GetString("SuppCompte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Donnez le budget du thème en bas de la page.
        /// </summary>
        public static string tapezBugetTheme {
            get {
                return ResourceManager.GetString("tapezBugetTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Terminer.
        /// </summary>
        public static string terminer {
            get {
                return ResourceManager.GetString("terminer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thématiques.
        /// </summary>
        public static string thematique {
            get {
                return ResourceManager.GetString("thematique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Appuyer sur entrée pour ajouter la thématique.
        /// </summary>
        public static string thematiqueInfo {
            get {
                return ResourceManager.GetString("thematiqueInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Au moins une thématique est requise.
        /// </summary>
        public static string thematiqueRequise {
            get {
                return ResourceManager.GetString("thematiqueRequise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette thématique n&apos;a pas de proposition.
        /// </summary>
        public static string thematiqueSansProposition {
            get {
                return ResourceManager.GetString("thematiqueSansProposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thème.
        /// </summary>
        public static string theme {
            get {
                return ResourceManager.GetString("theme", resourceCulture);
            }
        }
    }
}
