//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.democratia.view.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.democratia.view.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse postle.
        /// </summary>
        public static string adress {
            get {
                return ResourceManager.GetString("adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quelle bonne idée de nous rejoindre.
        /// </summary>
        public static string BonneNouvelle {
            get {
                return ResourceManager.GetString("BonneNouvelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vérifier que tous les champs soient complets.
        /// </summary>
        public static string champComplet {
            get {
                return ResourceManager.GetString("champComplet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Création de compte réussi, Connectez-vous maintenant.
        /// </summary>
        public static string compteCree {
            get {
                return ResourceManager.GetString("compteCree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;adresse mail es déjà créé.
        /// </summary>
        public static string compteExistantErreur {
            get {
                return ResourceManager.GetString("compteExistantErreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Oui, supprimez mon compte.
        /// </summary>
        public static string confirmeSupp {
            get {
                return ResourceManager.GetString("confirmeSupp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Se connecter.
        /// </summary>
        public static string connecter {
            get {
                return ResourceManager.GetString("connecter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de connexion inattendu.
        /// </summary>
        public static string connexionErreur {
            get {
                return ResourceManager.GetString("connexionErreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrer.
        /// </summary>
        public static string enregistrer {
            get {
                return ResourceManager.GetString("enregistrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors de la création du compte.
        /// </summary>
        public static string erreurCreation {
            get {
                return ResourceManager.GetString("erreurCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors de la récupération des données.
        /// </summary>
        public static string erreurDonne {
            get {
                return ResourceManager.GetString("erreurDonne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur inattendu, veuillez revenir ultérieurement.
        /// </summary>
        public static string erreurInattendu {
            get {
                return ResourceManager.GetString("erreurInattendu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez saisir votre adresse mail.
        /// </summary>
        public static string errorMailMessage {
            get {
                return ResourceManager.GetString("errorMailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez saisir votre mot de passe.
        /// </summary>
        public static string errorPasswordMessage {
            get {
                return ResourceManager.GetString("errorPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le format de l&apos;adresse mail est incorrecte.
        /// </summary>
        public static string formatEmail {
            get {
                return ResourceManager.GetString("formatEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le format du mot de passe est incorrecte.
        /// </summary>
        public static string formatMotDePasse {
            get {
                return ResourceManager.GetString("formatMotDePasse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mes groupes.
        /// </summary>
        public static string groupe {
            get {
                return ResourceManager.GetString("groupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse mail.
        /// </summary>
        public static string Identifiant {
            get {
                return ResourceManager.GetString("Identifiant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M&apos;inscrire.
        /// </summary>
        public static string inscription {
            get {
                return ResourceManager.GetString("inscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisissez une langue.
        /// </summary>
        public static string Langage {
            get {
                return ResourceManager.GetString("Langage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à courriel.
        /// </summary>
        public static string mail {
            get {
                return ResourceManager.GetString("mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Êtes-vous sûr(e) de vouloir supprimer le compte ?.
        /// </summary>
        public static string mauvaiseNouvelle {
            get {
                return ResourceManager.GetString("mauvaiseNouvelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe incorrecte.
        /// </summary>
        public static string mauvaisMdp {
            get {
                return ResourceManager.GetString("mauvaisMdp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe.
        /// </summary>
        public static string Mdp {
            get {
                return ResourceManager.GetString("Mdp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier mon compte.
        /// </summary>
        public static string ModifCompte {
            get {
                return ResourceManager.GetString("ModifCompte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer en un !.
        /// </summary>
        public static string NewCompte {
            get {
                return ResourceManager.GetString("NewCompte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer un groupe.
        /// </summary>
        public static string NewGroupe {
            get {
                return ResourceManager.GetString("NewGroupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        public static string Nom {
            get {
                return ResourceManager.GetString("Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pas d&apos;utilisateur trouvé.
        /// </summary>
        public static string noUser {
            get {
                return ResourceManager.GetString("noUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pas de compte ?.
        /// </summary>
        public static string pasCompte {
            get {
                return ResourceManager.GetString("pasCompte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à prénom.
        /// </summary>
        public static string prenom {
            get {
                return ResourceManager.GetString("prenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer mon compte.
        /// </summary>
        public static string SuppCompte {
            get {
                return ResourceManager.GetString("SuppCompte", resourceCulture);
            }
        }
    }
}
