<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0-ios;</TargetFrameworks>
    <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks)net10.0-android;net10.0-windows10.0.19041.0;</TargetFrameworks>
    <!--<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('OSX'))">$(TargetFrameworks)net10.0-maccatalyst</TargetFrameworks> à décommenter en prod--> 
	<TargetFrameworks>$(TargetFrameworks)net10.0-maccatalyst</TargetFrameworks>
	<EnablePreviewFeatures>true</EnablePreviewFeatures>
	<MauiXamlInflator>SourceGen</MauiXamlInflator>
	<UseMaterial3>true</UseMaterial3>
    <!-- Note for MacCatalyst:
		The default runtime is maccatalyst-x64, except in Release config, in which case the default is maccatalyst-x64;maccatalyst-arm64.
		When specifying both architectures, use the plural <RuntimeIdentifiers> instead of the singular <RuntimeIdentifier>.
		The Mac App Store will NOT accept apps with ONLY maccatalyst-arm64 indicated;
		either BOTH runtimes must be indicated or ONLY macatalyst-x64. -->
    <!--<RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers>-->
	  <!-- iOS Entitlements: For push notifications to work on iOS, you need proper provisioning profiles.
	     In a production app, rename Entitlements.plist.txt to Entitlements.plist and ensure you have:
	     1. A valid Apple Developer account
	     2. App ID configured with Push Notifications capability  
	     3. Provisioning profile that includes Push Notifications
	     4. Proper code signing certificate
	     The entitlements file has been renamed to .txt to allow the sample to build without these requirements. -->
	  
	  <OutputType Condition="'$(TargetFramework)' == 'net10.0-windows10.0.19041.0' &#xD;&#xA;                        Or '$(TargetFramework)' == 'net10.0-android' &#xD;&#xA;                        Or '$(TargetFramework)' == 'net10.0-ios' &#xD;&#xA;                        Or '$(TargetFramework)' == 'net10.0-maccatalyst' &#xD;&#xA;                        Or '$(TargetFramework)' == 'net10.0-tizen'">Exe</OutputType>
    <RootNamespace>com.koyok.democratia.view</RootNamespace>
    <UseMaui>true</UseMaui>
    <SingleProject>true</SingleProject>
    <ImplicitUsings>enable</ImplicitUsings>
	  <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
    <!-- Display name -->
    <ApplicationTitle>com.koyok.democratia.view</ApplicationTitle>
    <!-- App Identifier -->
    <ApplicationId>com.companyname.com.koyok.democratia.view</ApplicationId>
    <!-- Versions -->
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
    <!-- To develop, package, and publish an app to the Microsoft Store, see: https://aka.ms/MauiTemplateUnpackaged -->
    <WindowsPackageType>None</WindowsPackageType>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">23.0</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
    <TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
    <UserSecretsId>c026941f-3829-4e74-bd61-6855fd2a538c</UserSecretsId>
	  <AssemblyName>com.koyok.democratia.view</AssemblyName>
	  <ArchiveOnBuild>false</ArchiveOnBuild>
	  <DefaultLanguage>fr-FR</DefaultLanguage>
  </PropertyGroup>
	<PropertyGroup Condition="$(TargetFramework.Contains('-maccatalyst')) and '$(Configuration)' == 'Debug'">
		<EnableCodeSigning>true</EnableCodeSigning>
		<CodesignKey>Apple Development</CodesignKey>
		<CodesignEntitlements>Platforms\MacCatalyst\Entitlements.plist</CodesignEntitlements>
	</PropertyGroup>

	<PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Debug' and '$(RuntimeIdentifier)' == 'ios-arm64'">
		<EnableCodeSigning>true</EnableCodeSigning>
		<CodesignKey>Apple Development</CodesignKey>
		<CodesignEntitlements>Platforms\iOS\Entitlements.plist</CodesignEntitlements>
	</PropertyGroup>
	<PropertyGroup Condition="'$(TargetFramework)' == 'net10.0-maccatalyst' And '$(Configuration)' == 'Release'">
		<RuntimeIdentifier>maccatalyst-arm64</RuntimeIdentifier>
		<SelfContained>true</SelfContained>
		<CreatePackage>true</CreatePackage>
		<EnableCodeSigning>false</EnableCodeSigning>
		<EnablePackageSigning>false</EnablePackageSigning>
		<_RemoteBuildSteps>true</_RemoteBuildSteps>
	</PropertyGroup>
	<PropertyGroup>
		<ApplicationIdGuid>7b28a8d1-xxxx-xxxx-xxxx-xxxxxxxxxxxx</ApplicationIdGuid>
		<NeutralLanguage>fr</NeutralLanguage>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0-ios|AnyCPU'">
	  <ApplicationId>com.koyok.democratia</ApplicationId>
	  <ApplicationTitle>Democratia</ApplicationTitle>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0-android|AnyCPU'">
	  <ApplicationId>com.koyok.democratia</ApplicationId>
	  <ApplicationTitle>Democratia</ApplicationTitle>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0-windows10.0.19041.0|AnyCPU'">
	  <ApplicationId>com.koyok.democratia</ApplicationId>
	  <ApplicationTitle>Democratia</ApplicationTitle>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-ios|AnyCPU'">
	  <ApplicationId>com.koyok.democratia</ApplicationId>
	  <ApplicationTitle>Democratia</ApplicationTitle>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-android|AnyCPU'">
	  <ApplicationId>com.koyok.democratia</ApplicationId>
	  <ApplicationTitle>Democratia</ApplicationTitle>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-windows10.0.19041.0|AnyCPU'">
	  <ApplicationId>com.koyok.democratia</ApplicationId>
	  <ApplicationTitle>Democratia</ApplicationTitle>
	</PropertyGroup>
  <ItemGroup>
    <!-- App Icon -->
    <MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#2D0004" />
    <!-- Splash Screen -->
    <MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#2D0004" BaseSize="128,128" />
    <!-- Images -->
    <MauiImage Include="Resources\Images\*" />
    <MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />
    <!-- Custom Fonts -->
    <MauiFont Include="Resources\Fonts\*" />
    <!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
    <MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
	<ItemGroup>
		<AndroidResource Include="Platforms\Android\Resources\xml\network_security_config.xml" />
	</ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Maui" Version="15.0.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.11" />
    <PackageReference Include="Microsoft.Maui.Controls" Version="10.0.90" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.11" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Syncfusion.Maui.Inputs" Version="34.2.3" />
    <PackageReference Include="Syncfusion.Maui.Toolkit" Version="1.0.10" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\com.koyok.democratia.core\com.koyok.democratia.core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Platforms\MacCatalyst\AppDelegate.cs">
      <ExcludeFromCurrentConfiguration>false</ExcludeFromCurrentConfiguration>
    </Compile>
    <Compile Update="Platforms\MacCatalyst\DeviceInstallationService.cs">
      <ExcludeFromCurrentConfiguration>false</ExcludeFromCurrentConfiguration>
    </Compile>
    <Compile Update="Platforms\MacCatalyst\NSDataExtensions.cs">
      <ExcludeFromCurrentConfiguration>false</ExcludeFromCurrentConfiguration>
    </Compile>
    <Compile Update="Resources\Localization\AppResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AppResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Views\Component\EntryComponent.xaml.cs">
      <DependentUpon>EntryComponent.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Component\internaute\Formulaire.xaml.cs">
      <DependentUpon>Formulaire.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\groupe\DecideurPage.xaml.cs">
      <DependentUpon>DecideurPage.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\groupe\Membre.xaml.cs">
      <DependentUpon>Membre.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\groupe\ParametrePage.xaml.cs">
      <DependentUpon>ParametrePage.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\internaute\CreerGroupe\TroisiemeCreationPage.xaml.cs">
      <DependentUpon>TroisiemeCreationPage.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\internaute\gestionCompte\CreationPage.xaml.cs">
      <DependentUpon>CreationPage.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\internaute\CreerGroupe\DeuxiemeCreationPage.xaml.cs">
      <DependentUpon>DeuxiemeCreationPage.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\internaute\CreerGroupe\PremiereCreationPage.xaml.cs">
      <DependentUpon>PremiereCreationPage.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\internaute\gestionCompte\HomeGestionPage.xaml.cs">
      <DependentUpon>HomeGestionPage.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\internaute\gestionCompte\ModifierGestionPage.xaml.cs">
      <DependentUpon>ModifierGestionPage.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\internaute\gestionCompte\PreferencePage.xaml.cs">
      <DependentUpon>PreferencePage.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\MainPage.xaml.cs">
      <DependentUpon>MainPage.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\internaute\LoginPage.xaml.cs">
      <DependentUpon>LoginPage.xaml</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Resources\Localization\AppResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>AppResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <MauiXaml Update="Resources\Dimension\Dimension.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\Component\groupe\CommentaireComponent.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\Component\groupe\DecideurThematique.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\Component\EntryComponent.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\Component\internaute\Formulaire.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\Component\groupe\PropositionCard.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\Component\LoadingArc.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\Component\LoadingComponent.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\Component\RefreshView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\groupe\DecideurPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\groupe\Membre.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\groupe\NouvelleProposition.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\groupe\ParametrePage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\groupe\PropositionPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\internaute\CreerGroupe\DeuxiemeCreationPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\internaute\CreerGroupe\PremiereCreationPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\internaute\CreerGroupe\TroisiemeCreationPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\internaute\gestionCompte\HomeGestionPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\internaute\gestionCompte\ModifierGestionPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\internaute\gestionCompte\PreferencePage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\MainPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0-android'">
    <PackageReference Include="Xamarin.Firebase.Messaging">
      <Version>125.1.1</Version>
    </PackageReference>
  <PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData" Version="2.11.0.1" />
  <PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData.Core" Version="2.11.0.1" />
  <PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData.Core.Ktx" Version="2.11.0.1" />
  <PackageReference Include="Xamarin.AndroidX.Lifecycle.ViewModel" Version="2.11.0.1" />
  <PackageReference Include="Xamarin.AndroidX.Lifecycle.ViewModel.Ktx" Version="2.11.0.1" />
  <PackageReference Include="Xamarin.AndroidX.Lifecycle.Runtime" Version="2.11.0.1" />
  <PackageReference Include="Xamarin.AndroidX.Lifecycle.Runtime.Ktx" Version="2.11.0.1" />
  <PackageReference Include="Xamarin.AndroidX.Lifecycle.Runtime.Ktx.Android" Version="2.11.0.1" />
  <PackageReference Include="Xamarin.AndroidX.Lifecycle.Process" Version="2.11.0.1" />

  <PackageReference Include="Xamarin.AndroidX.Fragment" Version="1.8.9.3" />
  <PackageReference Include="Xamarin.AndroidX.Fragment.Ktx" Version="1.8.9.4" />

  <PackageReference Include="Xamarin.AndroidX.Activity" Version="1.13.0.1" />
  <PackageReference Include="Xamarin.AndroidX.Activity.Ktx" Version="1.13.0.1" />

  <PackageReference Include="Xamarin.AndroidX.Collection.Jvm" Version="1.6.0.1" />
  <PackageReference Include="Xamarin.AndroidX.Collection.Ktx" Version="1.6.0.1" />

  <PackageReference Include="Xamarin.AndroidX.SavedState" Version="1.5.0.1" />
  <PackageReference Include="Xamarin.AndroidX.SavedState.SavedState.Ktx" Version="1.5.0.1" />
  </ItemGroup>
<ItemGroup>
	  <GoogleServicesJson Include="Platforms\Android\google-services.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </GoogleServicesJson>
	</ItemGroup>
</Project>