name: unitTest

on:
  pull_request:
    branches: [ main, "developpment" ]
  push:
    branches: ["developpment"]


jobs:
  test-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        uitest: 
          - "UITests.Android/UITests.Android.csproj"
          - "UITests.Windows/UITests.Windows.csproj"
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      - name: Install MAUI Workload
        run: dotnet workload install maui
      - name: Build and Run UITests
        run: |
          dotnet build com.democratia.mauiTest/${{matrix.uitest}}
          dotnet test  com.democratia.mauiTest/${{matrix.uitest}} --no-build --verbosity normal

  test-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        uitest: 
          - "UITests.macOS/UITests.macOS.csproj"
          - "UITests.iOS/UITests.iOS.csproj"
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      - name: Install MAUI Workload
        run: dotnet workload install maui
      - name: Create appsettings.production.json
        run: | 
          echo '${{ secrets.APPSETTINGS_PRODUCTION_JSON }}' > ./com.democratia.core/appsettings.production.json
          echo '${{ secrets.APPSETTINGS_JSON }}' > ./com.democratia.core/appsettings.json
          echo '${{ secrets.APPSETTINGS_DEVELOPPEMENT_JSON }}' > ./com.democratia.core/appsettings.developpement.json
      - name: Build and Run UITests
        run: |
          dotnet build com.democratia.mauiTest/${{matrix.uitest}} -c Release
          dotnet test  com.democratia.mauiTest/${{matrix.uitest}} --no-build --verbosity normal
